// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYeSz0GO9HTKhDqmkeNsuve1HuGxFvz4',
    appId: '1:211638312048:web:0e7e4cc01f0b7c859a28b5',
    messagingSenderId: '211638312048',
    projectId: 'tracker-ba52f',
    authDomain: 'tracker-ba52f.firebaseapp.com',
    storageBucket: 'tracker-ba52f.appspot.com',
    measurementId: 'G-B7WVEQ8RSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFBm_fWdZhmJW2mpm0CabJxT1ngjvzlbQ',
    appId: '1:211638312048:android:960806e85658b62f9a28b5',
    messagingSenderId: '211638312048',
    projectId: 'tracker-ba52f',
    storageBucket: 'tracker-ba52f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi15kSzr80eq8rwlbdSq7nOQ8fi753_wY',
    appId: '1:211638312048:ios:d11ffb2dd6b8dd099a28b5',
    messagingSenderId: '211638312048',
    projectId: 'tracker-ba52f',
    storageBucket: 'tracker-ba52f.appspot.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi15kSzr80eq8rwlbdSq7nOQ8fi753_wY',
    appId: '1:211638312048:ios:e7b8d2878098983d9a28b5',
    messagingSenderId: '211638312048',
    projectId: 'tracker-ba52f',
    storageBucket: 'tracker-ba52f.appspot.com',
    iosBundleId: 'com.example.tracker.RunnerTests',
  );
}
